books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("list/", views.BookListView.as_view(), name="list"),
    path(
        "<int:pk>/detail/",
        views.BookDetailView.as_view(),
        name="detail",
    ),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path(
        "<int:pk>/update/",
        views.BookUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.BookDeleteView.as_view(),
        name="delete",
    ),
]

library_management/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("authors/", include("authors.urls")),
    path("books/", include("books.urls")),
    path("categories/", include("categories.urls")),
    path("loans/", include("loans.urls")),
    path("patrons/", include("patrons.urls")),
]

loans/urls.py
from django.urls import path

from . import views

app_name = "loans"

urlpatterns = [
    path("list/", views.LoanListView.as_view(), name="list"),
    path(
        "<int:pk>/detail/",
        views.LoanDetailView.as_view(),
        name="detail",
    ),
    path("create/", views.LoanCreateView.as_view(), name="create"),
    path(
        "<int:pk>/update/",
        views.LoanUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.LoanDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:pk>/return/",
        views.LoanReturnView.as_view(),
        name="return",
    ),
    path(
        "returned/",
        views.LoanReturnedListView.as_view(),
        name="returned-list",
    ),
    path(
        "<int:pk>/returned/detail/",
        views.LoanReturnedDetailView.as_view(),
        name="returned-detail",
    ),
]

loans/models.py
from django.db import models, transaction
from django.utils import timezone

from books.models import Book
from patrons.models import Patron


class Loan(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.PROTECT,
        related_name="loans",
        verbose_name="Livro",
    )
    patron = models.ForeignKey(
        Patron,
        on_delete=models.PROTECT,
        related_name="loans",
        verbose_name="Emprestado para",
    )
    loan_date = models.DateTimeField("Data do Empréstimo", auto_now_add=True)
    due_date = models.DateTimeField("Data prevista para devolução")
    is_returned = models.BooleanField("Devolvido?", default=False)
    return_date = models.DateTimeField("Data da devolução", blank=True, null=True)
    notes = models.TextField("Observações", blank=True)

    class Meta:
        verbose_name = "Empréstimo"
        verbose_name_plural = "Empréstimos"

    def __str__(self):
        return f'Empréstimo de "{self.book}" para {self.patron.name} em {
            self.loan_date.strftime("%d/%m/%Y")
        }'

    def save(self, *args, **kwargs):
        if not self.pk:
            with transaction.atomic():
                if self.book.quantity > 0:
                    self.book.quantity -= 1
                    self.book.save()

                    super().save(*args, **kwargs)
                else:
                    raise ValueError(
                        "Não há exemplares deste livro disponíveis para empréstimo."
                    )
            return

        else:
            if self.is_returned and not self.return_date:
                self.return_date = timezone.now()
            elif not self.is_returned and self.return_date:
                self.return_date = None

            old_loan = Loan.objects.get(pk=self.pk)

            if self.is_returned and not old_loan.is_returned:
                with transaction.atomic():
                    self.book.quantity += 1
                    self.book.save()
                    super().save(*args, **kwargs)

            elif not self.is_returned and old_loan.is_returned:
                with transaction.atomic():
                    if self.book.quantity > 0:
                        self.book.quantity -= 1
                        self.book.save()
                        super().save(*args, **kwargs)
                    else:
                        raise ValueError(
                            "Não é possível reverter a devolução, pois não há estoque."
                        )

            else:
                super().save(*args, **kwargs)

loans/forms.py
from django import forms
from django.core.exceptions import ValidationError

from . import models


class LoanForm(forms.ModelForm):
    class Meta:
        model = models.Loan
        fields = [
            "book",
            "patron",
            "due_date",
            "is_returned",
            "notes",
        ]
        labels = {
            "book": "Livro",
            "patron": "Leitor",
            "due_date": "Previsão de Devolução",
            "is_returned": "Devolvido?",
            "notes": "Observações",
        }
        widgets = {
            "book": forms.Select(attrs={"class": "form-select"}),
            "patron": forms.Select(attrs={"class": "form-select"}),
            "due_date": forms.DateTimeInput(
                attrs={"class": "form-control", "type": "datetime-local"}
            ),
            "is_returned": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "notes": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                }
            ),
        }

    def clean(self):
        cleaned_data = super().clean()
        book = cleaned_data.get("book")

        if book and not self.instance.pk:
            if book.quantity < 1:
                raise ValidationError(
                    "Não há exemplares disponíveis para empréstimo deste livro."
                )

        return cleaned_data

loans/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models


class LoanListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Loan
    template_name = "loans/loan_list.html"
    context_object_name = "loans"
    permission_required = "loans.view_loan"

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("q")
        queryset = queryset.filter(is_returned=False)

        if search:
            queryset = queryset.filter(
                Q(book__title__icontains=search)
                | Q(patron__name__icontains=search)
                | Q(patron__cpf__icontains=search)
            )

        return queryset


class LoanDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Loan
    template_name = "loans/loan_detail.html"
    permission_required = "loans.view_loan"


class LoanCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView
):
    model = models.Loan
    template_name = "loans/loan_create.html"
    form_class = forms.LoanForm
    success_url = reverse_lazy("loans:list")
    permission_required = "loans.add_loan"
    success_message = "Empréstimo cadastrado com sucesso."

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields.pop("is_returned")
        return form


class LoanUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = models.Loan
    template_name = "loans/loan_update.html"
    form_class = forms.LoanForm
    success_url = reverse_lazy("loans:list")
    permission_required = "loans.change_loan"
    success_message = "Empréstimo atualizado com sucesso."

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields.pop("is_returned")
        return form


class LoanDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Loan
    template_name = "loans/loan_delete.html"
    success_url = reverse_lazy("loans:list")
    permission_required = "loans.delete_loan"

    def form_valid(self, form):
        messages.success(
            self.request,
            f"O empréstimo para '{self.object.patron.name}' foi deletado com sucesso.",
        )
        return super().form_valid(form)


class LoanReturnView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = models.Loan
    template_name = "loans/loan_return.html"
    form_class = forms.LoanForm
    success_url = reverse_lazy("loans:list")
    permission_required = "loans.view_loan"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        for field in ["patron", "due_date", "is_returned"]:
            form.fields.pop(field)
        return form

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_returned = True
        self.object.save()
        messages.success(
            self.request,
            f"O livro '{self.object.book.title}' foi devolvido com sucesso.",
        )
        return super().form_valid(form)


class LoanReturnedListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Loan
    template_name = "loans/loan_returned_list.html"
    context_object_name = "loans"
    permission_required = "loans.view_loan"

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("q")
        queryset = queryset.filter(is_returned=True)

        if search:
            queryset = queryset.filter(
                Q(book__title__icontains=search)
                | Q(patron__name__icontains=search)
                | Q(patron__cpf__icontains=search)
            )

        return queryset


class LoanReturnedDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Loan
    template_name = "loans/loan_returned_detail.html"
    permission_required = "loans.view_loan"

loans/templates/loans/loan_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Empréstimo</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Empréstimo</button>
            </form>
        </div>
    </div>
    <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Empréstimos</a>
</div>

{% endblock %}

loans/templates/loans/loan_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Deletar Empréstimo</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja deletar o Empréstimo <strong>{{ object.book }} para {{ object.patron.name }}</strong>?</p>

                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Deletar</button>
                </form>
                
            </div>
            
        </div>
        <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Empréstimos</a>
    </div>



{% endblock %}

loans/templates/loans/loan_detail.html
{% extends 'base.html' %}

{% block title %}Detalhes do Empréstimo: {{ object.book }}{% endblock %}

{% block content %}
<h4 class="mb-4">{{ object.book }}</h4>

<div class="card mb-3">
    <div class="card-body">
        <p class="card-text"><strong>Leitor:</strong> {{ object.patron.name }}</p>
        <p class="card-text"><strong>CPF:</strong> {{ object.patron.cpf }}</p>
        <p class="card-text"><strong>Celular:</strong> {{ object.patron.phone_number }}</p>
        <p class="card-text"><strong>Data do Empréstimo:</strong> {{ object.loan_date }}</p>
        <p class="card-text"><strong>Data Prevista para Devolução:</strong> {{ object.due_date }}</p>
        <p class="card-text"><strong>Devolvido:</strong> {% if loan.is_returned %}Sim{% else %}Não{% endif %}</p>
        <p class="card-text"><strong>Observações:</strong> {{ object.notes|default:"Nenhuma observação disponível." }}</p>

        <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3">Voltar para a lista</a>
    </div>
</div>
{% endblock %}

loans/templates/loans/loan_list.html
{% extends 'base.html' %}

{% block title %}
Empréstimos
{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'loans:list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="q" placeholder="Livro ou Leitor" value="{{ request.GET.q }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col-md-6">
    {% if perms.loans.add_loan %}
      <a href="{% url 'loans:create' %}" class="btn btn-success float-end">
          <i class="bi bi-plus"></i> Novo Empréstimo
      </a>
    
      <a href="{% url 'loans:returned-list' %}" class="btn btn-outline-primary mb-3">Ver Livros Devolvidos</a>
    {% endif %}
    </div>

</div>



<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Livro</th>
                <th>Leitor</th>
                <th>CPF</th>
                <th>Data de Empréstimo</th>
                <th>Data Prevista de Devolução</th>
                <th>Devolvido</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for loan in loans %}
                <tr>
                    <td>{{ loan.id }}</td>
                    <td>{{ loan.book.title}}</td>
                    <td>{{ loan.patron.name }}</td>
                    <td>{{ loan.patron.cpf }}</td>
                    <td>{{ loan.loan_date }}</td>
                    <td>{{ loan.due_date }}</td>
                    <td>{% if loan.is_returned %}Sim{% else %}Não{% endif %}</td>
                    <td>
                          {% if perms.loans.view_loan %}
                            <a href="{% url 'loans:detail' loan.id %}" class="btn btn-info btn-sm">
                                <i class="bi bi-eye"></i>
                            </a>
                          {% endif %}
                          {% if perms.loans.change_loan %}
                             <a href="{% url 'loans:update' loan.id %}" class="btn btn-warning btn-sm">
                                <i class="bi bi-pencil"></i>
                            </a>
                          {% endif %}
                          {% if perms.loans.delete_loan %}
                            <a href="{% url 'loans:return' loan.id %}" class="btn btn-success btn-sm">Devolver</a>
                          {% endif %}
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

loans/templates/loans/loan_return.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Registrar Devolução</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja registrar a devolução do livro: <strong>{{ object.book.title }} emprestado para {{ object.patron.name }}</strong>?</p>

                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success mt-3">Registrar Devolução</button>
                </form>
                
            </div>
            
        </div>
        <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Empréstimos</a>
    </div>



{% endblock %}

loans/templates/loans/loan_returned_detail.html
{% extends 'base.html' %}

{% block title %}Detalhes do Empréstimo: {{ object.book }}{% endblock %}

{% block content %}
<h4 class="mb-4">{{ object.book }}</h4>

<div class="card mb-3">
    <div class="card-body">
        <p class="card-text"><strong>Leitor:</strong> {{ object.patron.name }}</p>
        <p class="card-text"><strong>CPF:</strong> {{ object.patron.cpf }}</p>
        <p class="card-text"><strong>Celular:</strong> {{ object.patron.phone_number }}</p>
        <p class="card-text"><strong>Data do Empréstimo:</strong> {{ object.loan_date }}</p>
        <p class="card-text"><strong>Data Prevista para Devolução:</strong> {{ object.due_date }}</p>
        <p class="card-text"><strong>Devolvido:</strong> {% if loan.is_returned %}Sim{% else %}Não{% endif %}</p>
        <p class="card-text"><strong>Observações:</strong> {{ object.notes|default:"Nenhuma observação disponível." }}</p>

        <a href="{% url 'loans:returned-list' %}" class="btn btn-secondary mt-3">Voltar para a lista</a>
    </div>
</div>
{% endblock %}

loans/templates/loans/loan_returned_list.html
{% extends 'base.html' %}

{% block content %}
 <h6 class="display-6">Livros Já Devolvidos</h6>
<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'loans:returned-list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="q" placeholder="Livro ou Leitor" value="{{ request.GET.q }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

</div>
   
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Livro</th>
                    <th>Leitor</th>
                    <th>CPF</th>
                    <th>Data de Empréstimo</th>
                    <th>Data da Devolução</th>
                    <th>Observações</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for loan in loans %}
                <tr>
                    <td>{{ loan.id }}</td>
                    <td>{{ loan.book.title }}</td>
                    <td>{{ loan.patron.name }}</td>
                    <td>{{ loan.patron.cpf }}</td>
                    <td>{{ loan.loan_date }}</td>
                    <td>{{ loan.return_date }}</td>
                    <td>{{ loan.notes }}</td>
                    <td>
                            <a href="{% url 'loans:returned-detail' loan.id %}" class="btn btn-info btn-sm">
                                <i class="bi bi-eye"></i>
                            </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">Nenhum livro devolvido encontrado.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3 float-end">Voltar para Empréstimos Ativos</a>

{% endblock %}

loans/templates/loans/loan_update.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Editar Empréstimo</h3>

        <div class="card">
            <div class="card-body">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Salvar Empréstimo</button>
                </form>
            </div>
        </div>
        <a href="{% url 'loans:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Empréstimos</a>
    </div>

{% endblock %}