authors/urls.py
from django.urls import path

from . import views

app_name = "authors"

urlpatterns = [
    path("list/", views.AuthorListView.as_view(), name="list"),
    path(
        "<int:pk>/detail/",
        views.AuthorDetailView.as_view(),
        name="detail",
    ),
    path(
        "create/",
        views.AuthorCreateView.as_view(),
        name="create",
    ),
    path(
        "<int:pk>/update/",
        views.AuthorUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.AuthorDeleteView.as_view(),
        name="delete",
    ),
]

books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("list/", views.BookListView.as_view(), name="list"),
    path(
        "<int:pk>/detail/",
        views.BookDetailView.as_view(),
        name="detail",
    ),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path(
        "<int:pk>/update/",
        views.BookUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.BookDeleteView.as_view(),
        name="delete",
    ),
]

library_management/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("authors/", include("authors.urls")),
    path("books/", include("books.urls")),
    path("categories/", include("categories.urls")),
    path("loans/", include("loans.urls")),
    path("patrons/", include("patrons.urls")),
]

authors/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField("Nome", max_length=250)
    description = models.TextField("Descrição", blank=True)

    class Meta:
        verbose_name = "Autor"
        verbose_name_plural = "Autores"

    def __str__(self):
        return self.name

authors/forms.py
from django import forms

from . import models


class AuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = [
            "name",
            "description",
        ]
        labels = {
            "name": "Nome",
            "description": "Descrição",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.TextInput(attrs={"class": "form-control"}),
        }

authors/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models


class AuthorListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Author
    template_name = "authors/author_list.html"
    context_object_name = "authors"
    permission_required = "authors.view_author"

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")

        if name:
            queryset = queryset.filter(name__icontains=name)

        return queryset


class AuthorCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView
):
    model = models.Author
    template_name = "authors/author_create.html"
    form_class = forms.AuthorForm
    success_url = reverse_lazy("authors:list")
    permission_required = "authors.add_author"
    success_message = "Autor(a) cadastrado(a) com sucesso!"


class AuthorDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Author
    template_name = "authors/author_detail.html"
    permission_required = "authors.view_author"


class AuthorUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = models.Author
    template_name = "authors/author_update.html"
    form_class = forms.AuthorForm
    success_url = reverse_lazy("authors:list")
    permission_required = "authors.change_author"
    success_message = "Dados do(a) autor(a) atualizados com sucesso!"


class AuthorDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Author
    template_name = "authors/author_delete.html"
    success_url = reverse_lazy("authors:list")
    permission_required = "authors.delete_author"

    def form_valid(self, form):
        messages.success(
            self.request,
            f"O(A) autor(a) '{self.object.name}' foi deletado(a) com sucesso.",
        )
        return super().form_valid(form)

authors/templates/authors/author_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Autor(a)</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Autor(a)</button>
            </form>
        </div>
    </div>
    <a href="{% url 'authors:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Autores</a>
</div>

{% endblock %}

authors/templates/authors/author_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Deletar Autor(a)</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja deletar o(a) Autor(a) <strong>{{ object.name }}</strong>?</p>

                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Deletar</button>
                </form>
                
            </div>
            
        </div>
        <a href="{% url 'authors:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Autores</a>
    </div>



{% endblock %}

authors/templates/authors/author_detail.html
{% extends 'base.html' %}

{% block title %}Detalhes do(a) Autor(a): {{ object.name }}{% endblock %}

{% block content %}
<h4 class="mb-4">{{ object.name }}</h4>

<div class="card mb-3">
    <div class="card-body">
        <p class="card-text"><strong>Descrição:</strong> {{ object.description|default:"Nenhuma descrição disponível." }}</p>

        <a href="{% url 'authors:list' %}" class="btn btn-secondary mt-3">Voltar para a lista de Autores</a>
    </div>
</div>
{% endblock %}

authors/templates/authors/author_list.html
{% extends 'base.html' %}

{% block title %}
Autores
{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'authors:list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col-md-6">
    {% if perms.authors.add_author %}
      <a href="{% url 'authors:create' %}" class="btn btn-success float-end">
          <i class="bi bi-plus"></i> Novo(a) Autor(a)
      </a>
    {% endif %}
    </div>

</div>



<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for author in authors %}
                <tr>
                    <td>{{ author.id }}</td>
                    <td>{{ author.name }}</td>
                    <td>{{ author.description }}</td>
                    <td>
                          {% if perms.authors.view_author %}
                            <a href="{% url 'authors:detail' author.id %}" class="btn btn-info btn-sm">
                                <i class="bi bi-eye"></i>
                            </a>
                          {% endif %}
                          {% if perms.authors.change_author %}
                             <a href="{% url 'authors:update' author.id %}" class="btn btn-warning btn-sm">
                                <i class="bi bi-pencil"></i>
                            </a>
                          {% endif %}
                          {% if perms.authors.delete_author %}
                            <a href="{% url 'authors:delete' author.id %}" class="btn btn-danger btn-sm">
                                <i class="bi bi-trash3"></i>
                            </a>
                          {% endif %}
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

authors/templates/authors/author_update.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Editar Autor(a)</h3>

        <div class="card">
            <div class="card-body">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Salvar Autor(a)</button>
                </form>
            </div>
        </div>
        <a href="{% url 'authors:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Autores</a>
    </div>

{% endblock %}