books/urls.py
from django.urls import path

from . import views

app_name = "books"

urlpatterns = [
    path("list/", views.BookListView.as_view(), name="list"),
    path(
        "<int:pk>/detail/",
        views.BookDetailView.as_view(),
        name="detail",
    ),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path(
        "<int:pk>/update/",
        views.BookUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.BookDeleteView.as_view(),
        name="delete",
    ),
]

categories/urls.py
from django.urls import path

from . import views

app_name = "categories"

urlpatterns = [
    path(
        "list/",
        views.CategoryListView.as_view(),
        name="list",
    ),
    path(
        "<int:pk>/detail/",
        views.CategoryDetailView.as_view(),
        name="detail",
    ),
    path(
        "create/",
        views.CategoryCreateView.as_view(),
        name="create",
    ),
    path(
        "<int:pk>/update/",
        views.CategoryUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="delete",
    ),
]

library_management/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("authors/", include("authors.urls")),
    path("books/", include("books.urls")),
    path("categories/", include("categories.urls")),
    path("loans/", include("loans.urls")),
    path("patrons/", include("patrons.urls")),
]

categories/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField("Nome", max_length=250)
    description = models.TextField("Descrição", blank=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.name

categories/forms.py
from django import forms

from . import models


class CategoryForm(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = [
            "name",
            "description",
        ]
        labels = {
            "name": "Nome",
            "description": "Descrição",
        }
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
            "description": forms.TextInput(attrs={"class": "form-control"}),
        }

categories/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models


class CategoryListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = models.Category
    template_name = "categories/category_list.html"
    context_object_name = "categories"
    permission_required = "categories.view_category"

    def get_queryset(self):
        queryset = super().get_queryset()
        name = self.request.GET.get("name")

        if name:
            queryset = queryset.filter(name__icontains=name)

        return queryset


class CategoryDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = models.Category
    template_name = "categories/category_detail.html"
    permission_required = "categories.view_category"


class CategoryCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, CreateView
):
    model = models.Category
    template_name = "categories/category_create.html"
    form_class = forms.CategoryForm
    success_url = reverse_lazy("categories:list")
    permission_required = "categories.add_category"
    success_message = "Categoria cadastrada com sucesso."


class CategoryUpdateView(
    LoginRequiredMixin, PermissionRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = models.Category
    template_name = "categories/category_update.html"
    form_class = forms.CategoryForm
    success_url = reverse_lazy("categories:list")
    permission_required = "categories.change_category"
    success_message = "Categoria atualizada com sucesso."


class CategoryDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = models.Category
    template_name = "categories/category_delete.html"
    success_url = reverse_lazy("categories:list")
    permission_required = "categories.delete_category"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(
                self.request,
                f"A categoria '{self.object.name}' foi deletada com sucesso.",
            )
            return redirect(self.success_url)
        except ProtectedError:
            messages.error(
                self.request,
                f"A categoria '{self.object.name}' não pode ser deletada, pois está sendo referenciada por um ou mais livros.",
            )
            return redirect(self.success_url)

categories/templates/categories/category_create.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-4">
    <h3 class="display-6">Cadastrar Categoria</h3>

    <div class="card">
        <div class="card-body">
            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Salvar Categoria</button>
            </form>
        </div>
    </div>
    <a href="{% url 'categories:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Categorias</a>
</div>

{% endblock %}

categories/templates/categories/category_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Deletar Categoria</h3>

        <div class="card">
            <div class="card-body">
                <p class="card-text">Tem certeza que deseja deletar a Categoria <strong>{{ object.name }}</strong>?</p>

                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger mt-3">Deletar</button>
                </form>
                
            </div>
            
        </div>
        <a href="{% url 'categories:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Categorias</a>
    </div>



{% endblock %}

categories/templates/categories/category_detail.html
{% extends 'base.html' %}

{% block title %}Detalhes da Categoria {{ object.name }}{% endblock %}

{% block content %}
<h4 class="mb-4">{{ object.name }}</h4>

<div class="card mb-3">
    <div class="card-body">
        <p class="card-text"><strong>Descrição:</strong> {{ object.description|default:"Nenhuma descrição disponível." }}</p>

        <a href="{% url 'categories:list' %}" class="btn btn-secondary mt-3">Voltar para a lista</a>
    </div>
</div>
{% endblock %}

categories/templates/categories/category_list.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-md-6">
        <form method="get" action="{% url 'categories:list' %}">
            <div class="input-group">
                <input type="text" class="form-control" name="name" placeholder="Nome" value="{{ request.GET.name }}">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-search"></i>
                </button>
            </div>
        </form>
    </div>

    <div class="col-md-6">
        {% if perms.categories.add_category %}
          <a href="{% url 'categories:create' %}" class="btn btn-success float-end">
             <i class="bi bi-plus"></i> Nova Categoria
          </a>
        {% endif %}
    </div>

</div>



<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.description }}</td>
                    <td>
                          {% if perms.categories.view_category %}
                            <a href="{% url 'categories:detail' category.id %}" class="btn btn-info btn-sm">
                                <i class="bi bi-eye"></i>
                            </a>
                          {% endif %}
                          {% if perms.categories.change_category %}
                             <a href="{% url 'categories:update' category.id %}" class="btn btn-warning btn-sm">
                                <i class="bi bi-pencil"></i>
                            </a>
                          {% endif %}
                          {% if perms.categories.delete_category %}
                            <a href="{% url 'categories:delete' category.id %}" class="btn btn-danger btn-sm">
                                <i class="bi bi-trash3"></i>
                            </a>
                          {% endif %}
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

categories/templates/categories/category_update.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-4">
        <h3 class="display-6">Editar Categoria</h3>

        <div class="card">
            <div class="card-body">
                <form method="post" class="form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Salvar Categoria</button>
                </form>
            </div>
        </div>
        <a href="{% url 'categories:list' %}" class="btn btn-secondary mt-3 float-end">Cancelar e Voltar para a Lista de Categorias</a>
    </div>

{% endblock %}